apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boilerplate
  template:
    metadata:
      labels:
        app: boilerplate
    spec:
      containers:
        - name: boilerplate
          image: gcr.io/{{secrets.GOOGLE_PROJECT_ID}}/boilerplate:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: boilerplate
